version: '3.8'

services:
  ai:
    build:
      context:
        ./ai
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  web:
    build:
      context:
        ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./web/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - ai
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge